G               = 6.67430e-11           # gravitational constant (m^3 kg^-1 s^-2)
D_EARTH_MOON    = 3.844e8               # average Earth-Moon distance (m)
M_EARTH         = 5.9722e24             # mass of Earth (kg) 
R_EARTH         = 6.371e6               # radius of Earth (m)
M_MOON          = 7.346e22              # mass of Moon (kg)
R_MOON          = 1.737e6               # radius of Moon (m)
V_MOON          = 1022                  # orbital speed of Moon (m/s)
i_MOON          = 5.145                 # Moon's inclination to Earth's orbit (°)

D_PLUTO_CHARON  = 1.9596e7              # average Pluto-Charon distance (m)
M_PLUTO         = 1.309e22              # mass of Pluto (kg)
R_PLUTO         = 1.1883e6              # radius of Pluto (m)
M_CHARON        = 1.5897e21             # mass of Charon (kg)
R_CHARON        = 606e3                 # radius of Charon (m)
V_CHARON        = 210                   # average orbital speed of Charon (m/s)
i_CHARON        = 112.783               # Charon's inclination to the ecliptic (°)
T_PLUTO_CHARON  = 6.387                 # orbital period of Charon around Pluto (days)