G               = 6.67430e-11           # gravitational constant (m^3 kg^-1 s^-2)
D_EARTH_MOON    = 3.844e8               # average Earth-Moon distance (m)
M_EARTH         = 5.9722e24             # mass of Earth (kg) 
R_EARTH         = 6.371e6               # radius of Earth (m)
M_MOON          = 7.346e22              # mass of Moon (kg)
R_MOON          = 1.737e6               # radius of Moon (m)
V_MOON          = 1022                  # orbital speed of Moon (m/s)
i_MOON          = 5.145                 # Moon's inclination to Earth's orbit (°)